# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specifications', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity_in_stock', models.IntegerField()),
                ('categories', models.ManyToManyField(to='goods.Category')),
            ],
        ),
    ]
